server:
  port: 8082

### DATABASE ###
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dbTestFile:5432/dbTestFile
    username: postgres
    password: admin
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
